export const DAILY_NOTE_PROMPTS = [
  // Hôm nay & quan sát
  'Hôm nay có điều gì làm mày chú ý mà bình thường sẽ bỏ qua?',
  'Có khoảnh khắc nào hôm nay đáng nhớ không?',
  'Điều gì hôm nay khác với mọi ngày?',
  'Hôm nay mày đã nhìn thấy điều gì thú vị?',
  'Có chuyện nhỏ nào hôm nay khiến mày bật cười?',
  'Có điều gì xảy ra hôm nay mà mày muốn nhớ lâu?',
  'Nếu chỉ được giữ lại một khoảnh khắc hôm nay, đó là gì?',
  'Hôm nay có điều gì khiến mày bất ngờ?',
  'Có điều gì hôm nay làm mày thay đổi suy nghĩ?',
  'Chi tiết nhỏ nào hôm nay đáng ghi lại?',
  'Hôm nay có gì mới?',
  'Hôm nay có gì lạ?',
  'Có điều gì mày vừa phát hiện ra?',
  'Có điều gì hôm nay mày muốn kể lại sau này?',
  'Nếu hôm nay có một tiêu đề, nó sẽ là gì?',
  'Điều đáng nhớ nhất trong vài giờ vừa rồi là gì?',
  'Hôm nay có thứ gì làm mày tò mò?',
  'Có điều gì mày nhìn thấy mà muốn tìm hiểu thêm?',
  'Hôm nay có khoảnh khắc nào mày muốn chụp lại bằng lời?',
  'Có điều gì rất bình thường nhưng hôm nay lại thấy khác?',

  // Công việc
  'Việc gì hôm nay tiến triển tốt hơn mày nghĩ?',
  'Có việc nào đang mắc ở đúng một điểm cụ thể?',
  'Việc gì đang tốn thời gian hơn giá trị nó mang lại?',
  'Có việc nào nên bỏ hẳn thay vì cố làm tiếp?',
  'Việc gì hôm nay đáng lặp lại vào ngày mai?',
  'Có bước nào trong công việc đang quá thủ công?',
  'Mày vừa giải quyết được vấn đề gì?',
  'Có việc nào tưởng khó nhưng hóa ra khá đơn giản?',
  'Việc gì đang bị trì hoãn mà lý do thật sự là gì?',
  'Có việc nào nên giao cho người khác?',
  'Có quy trình nào hôm nay làm mày khó chịu?',
  'Có việc nào mày đang làm theo thói quen nhưng không còn cần thiết?',
  'Điều gì hôm nay giúp mày làm việc nhanh hơn?',
  'Có quyết định công việc nào cần ghi lại lý do?',
  'Việc nào hôm nay tạo ra kết quả rõ nhất?',
  'Có việc nào mày làm nhiều nhưng chưa đo kết quả?',
  'Cái gì đang là nút thắt lớn nhất lúc này?',
  'Có việc nào chỉ cần 10 phút để giải quyết nhưng vẫn đang treo?',
  'Hôm nay có bài học vận hành nào đáng nhớ?',
  'Nếu mai chỉ làm được một việc quan trọng, nên là việc gì?',

  // Ý tưởng & sáng tạo
  'Có ý tưởng nào vừa lóe lên trong đầu?',
  'Nếu làm ngược lại cách hiện tại thì chuyện gì xảy ra?',
  'Có thứ gì mày thấy ngoài đời có thể biến thành sản phẩm?',
  'Có chi tiết nào từ một thương hiệu khác đáng học?',
  'Nếu phải làm phiên bản đơn giản hơn 50%, mày sẽ bỏ gì?',
  'Nếu phải làm phiên bản tốt hơn gấp đôi, mày sẽ thêm gì?',
  'Có ý tưởng nào nghe hơi điên nhưng đáng thử?',
  'Có thứ gì mày muốn làm nhưng chưa biết gọi tên?',
  'Nếu không bị giới hạn tiền bạc, mày sẽ thử gì?',
  'Nếu chỉ có 1 ngày để thử ý tưởng này, mày sẽ làm thế nào?',
  'Có cách nào biến việc đang làm thành sản phẩm?',
  'Có thứ gì khách hàng đang tự chế mà mày có thể làm tốt hơn?',
  'Có nhu cầu nào mày thấy lặp đi lặp lại?',
  'Có trải nghiệm nào ngoài đời khiến mày nghĩ “cái này nên làm tốt hơn”?',
  'Có thứ gì đang phổ biến ở chỗ khác nhưng chưa thấy nhiều quanh mày?',
  'Nếu kết hợp hai thứ mày đang làm, có thể thành gì?',
  'Có ý tưởng nào đáng lưu lại dù chưa làm ngay?',
  'Nếu phải đặt tên cho ý tưởng hôm nay, nó sẽ là gì?',
  'Có thứ gì mày muốn thử chỉ để xem chuyện gì xảy ra?',
  'Một phiên bản “rẻ hơn, nhanh hơn, đơn giản hơn” sẽ trông thế nào?',

  // Khách hàng & kinh doanh
  'Khách hàng hôm nay đang thật sự cần gì?',
  'Có câu hỏi nào khách hỏi nhiều lần gần đây?',
  'Khách đang mua sản phẩm hay đang mua một cảm giác nào đó?',
  'Có lý do nào khiến khách chưa mua mà mày chưa giải quyết?',
  'Điều gì khiến khách quay lại lần hai?',
  'Có điểm nào trong trải nghiệm mua hàng đang gây khó chịu?',
  'Khách đang phải chờ ở bước nào?',
  'Có thứ gì khách muốn nhưng chưa nói thẳng?',
  'Có phản hồi nào hôm nay đáng lưu lại?',
  'Có sản phẩm nào khách tự nhiên hỏi nhiều hơn?',
  'Có nhóm khách nào mày đang bỏ sót?',
  'Có món nào có thể bán kèm tự nhiên?',
  'Điều gì khiến sản phẩm của mày khác thật sự?',
  'Có chi tiết nào khách sẵn sàng trả thêm tiền?',
  'Có bước nào làm khách mất niềm tin?',
  'Khách nào hôm nay cho mày một insight mới?',
  'Có điều gì mày nghĩ khách quan tâm nhưng thực tế họ không quan tâm?',
  'Có thứ gì khách quan tâm mà mày đang xem nhẹ?',
  'Nếu khách chỉ nhớ một điều về sản phẩm, nên là gì?',
  'Có quyết định giá nào cần xem lại?',

  // Học tập
  'Hôm nay mày học được điều gì thật sự mới?',
  'Có khái niệm nào vừa hiểu ra sau một thời gian mơ hồ?',
  'Điều gì hôm nay khiến mày nhận ra mình từng hiểu sai?',
  'Có kiến thức nào nên áp dụng ngay thay vì chỉ nhớ?',
  'Nếu phải giải thích điều vừa học cho người khác, mày sẽ nói sao?',
  'Có câu nào trong sách hoặc video đáng ghi lại?',
  'Điều gì mày muốn tìm hiểu sâu hơn ngày mai?',
  'Có chủ đề nào mày đang tò mò hơn trước?',
  'Mày vừa học được mẹo gì tiết kiệm thời gian?',
  'Có kiến thức nào liên quan trực tiếp đến việc mày đang làm?',
  'Có điều gì vừa học nhưng chưa chắc đúng?',
  'Có câu hỏi nào mới xuất hiện sau khi học?',
  'Nếu chỉ nhớ một ý từ hôm nay, đó là gì?',
  'Có điều gì mày muốn tự kiểm chứng?',
  'Kiến thức nào hôm nay làm thay đổi cách mày làm việc?',
  'Có ví dụ thực tế nào giúp mày hiểu một khái niệm rõ hơn?',
  'Có điều gì nên ghi vào “nguyên tắc của tao”?',
  'Hôm nay mày học từ sai lầm nào?',
  'Có điều gì người khác làm tốt mà mày muốn học?',
  'Có kỹ năng nào mày muốn luyện 15 phút mỗi ngày?',

  // Sức khỏe & cơ thể
  'Hôm nay cơ thể mày cảm thấy thế nào?',
  'Có lúc nào năng lượng tụt rõ rệt không?',
  'Bữa ăn nào hôm nay làm mày no lâu nhất?',
  'Có món nào ăn xong cảm thấy không ổn?',
  'Buổi tập hôm nay bài nào cảm nhận cơ tốt nhất?',
  'Có bài nào hôm nay thấy yếu hơn bình thường?',
  'Giấc ngủ đêm qua ảnh hưởng hôm nay thế nào?',
  'Hôm nay mày uống đủ nước chưa?',
  'Có đau hoặc khó chịu ở đâu cần theo dõi?',
  'Hôm nay lúc nào mày thấy khỏe nhất?',
  'Có thời điểm nào trong ngày mày thấy uể oải?',
  'Bài tập nào hôm nay đáng giữ lại trong lịch?',
  'Có bài nào nên đổi vì không hợp?',
  'Hôm nay mày thấy sức mạnh tăng ở đâu?',
  'Có thói quen nhỏ nào làm cơ thể dễ chịu hơn?',
  'Hôm nay ăn gì khiến mày thấy ngon và hợp mục tiêu?',
  'Có thứ gì mày đang làm quá mức?',
  'Cơ thể đang muốn mày nghỉ hay vận động thêm?',
  'Có chỉ số sức khỏe nào nên bắt đầu theo dõi?',
  'Ngày mai mày muốn cơ thể cảm thấy thế nào?',

  // Cảm xúc
  'Cảm xúc nổi bật nhất hôm nay là gì?',
  'Có chuyện gì làm mày bực hơn mức nó đáng?',
  'Có điều gì khiến mày nhẹ nhõm?',
  'Hôm nay lúc nào mày thấy vui nhất?',
  'Có lúc nào mày thấy căng thẳng mà không rõ lý do?',
  'Điều gì hôm nay làm mày mất kiên nhẫn?',
  'Có chuyện gì mày đang nghĩ đi nghĩ lại?',
  'Có điều gì mày đang né tránh?',
  'Có điều gì mày đang lo nhưng thực ra chưa xảy ra?',
  'Hôm nay có lúc nào mày thấy tự hào về mình?',
  'Có lúc nào mày phản ứng hơi quá?',
  'Điều gì làm tâm trạng mày tốt lên nhanh nhất?',
  'Có người nào hôm nay ảnh hưởng mạnh tới tâm trạng của mày?',
  'Có điều gì mày nên buông bớt?',
  'Mày đang cần thêm điều gì: nghỉ, tập trung hay nói chuyện với ai đó?',
  'Có cảm xúc nào khó gọi tên hôm nay?',
  'Điều gì khiến mày cảm thấy bình tĩnh?',
  'Có việc gì làm xong khiến đầu óc nhẹ hơn?',
  'Hôm nay mày có đang quá khắt khe với bản thân không?',
  'Nếu mô tả tâm trạng hôm nay bằng 3 từ, đó là gì?',

  // Con người & mối quan hệ
  'Hôm nay ai làm mày ấn tượng?',
  'Có cuộc nói chuyện nào đáng nhớ?',
  'Có điều gì ai đó nói khiến mày suy nghĩ?',
  'Có ai mày nên nhắn một câu cảm ơn?',
  'Có người nào mày muốn gặp lại sớm?',
  'Hôm nay mày học được gì từ một người khác?',
  'Có ai đang cần mày phản hồi?',
  'Có cuộc nói chuyện nào mày nên xử lý khác đi?',
  'Có ai giúp mày mà mày chưa cảm ơn?',
  'Có người nào hôm nay cho mày năng lượng tốt?',
  'Có ai đang làm mày mất quá nhiều năng lượng?',
  'Có mối quan hệ nào cần dành thêm thời gian?',
  'Hôm nay mày có thực sự lắng nghe ai không?',
  'Có điều gì muốn nói nhưng chưa nói?',
  'Có ai mày muốn hỏi thêm một câu?',
  'Có người nào mày muốn học cách họ làm việc?',
  'Có ai hôm nay làm mày thay đổi góc nhìn?',
  'Có lời hứa nào với người khác cần nhớ?',
  'Có điều gì nhỏ mày có thể làm để một người vui hơn?',
  'Hôm nay mày muốn nhớ điều gì về một người nào đó?',

  // Tiền & chi tiêu
  'Hôm nay có khoản chi nào đáng suy nghĩ?',
  'Có thứ gì mày mua mà thật ra không cần?',
  'Có khoản nào chi ra nhưng rất đáng tiền?',
  'Có chi phí nào trong công việc đang phình lên?',
  'Có khoản nào có thể cắt mà không ảnh hưởng kết quả?',
  'Hôm nay mày kiếm tiền từ việc gì?',
  'Có nguồn thu nào đang tốt hơn trước?',
  'Có sản phẩm nào biên lợi nhuận thấp hơn mày tưởng?',
  'Có khoản đầu tư nhỏ nào đáng thử?',
  'Có món gì mày muốn mua nhưng nên chờ thêm?',
  'Có khoản chi định kỳ nào cần xem lại?',
  'Có cách nào làm cùng kết quả với chi phí thấp hơn?',
  'Có việc nào mày đang tự làm nhưng thuê ngoài sẽ rẻ hơn?',
  'Có khoản tiền nào đang bị kẹt?',
  'Có khách hàng hoặc đơn hàng nào cần thu tiền?',
  'Hôm nay có quyết định tài chính nào đáng ghi lại?',
  'Có thứ gì mày mua vì tiện chứ không phải vì cần?',
  'Có khoản nào nên đặt giới hạn?',
  'Có nguồn tiền nào mày chưa theo dõi đủ rõ?',
  'Nếu phải tiết kiệm 10% chi phí tháng này, mày cắt ở đâu?',

  // Sai lầm & cải thiện
  'Hôm nay mày làm sai điều gì?',
  'Sai lầm nào hôm nay đáng để không lặp lại?',
  'Có quyết định nào nếu làm lại mày sẽ chọn khác?',
  'Có việc gì mày làm quá vội?',
  'Có việc gì mày nghĩ quá lâu?',
  'Có chỗ nào mày thiếu thông tin trước khi quyết định?',
  'Có điều gì mày đang cố chữa triệu chứng thay vì nguyên nhân?',
  'Có vấn đề nào lặp lại lần thứ hai?',
  'Có thứ gì thất bại nhưng cho mày dữ liệu hữu ích?',
  'Điều gì hôm nay cho thấy một hệ thống đang có vấn đề?',
  'Có bước nào nên thêm checklist để tránh lỗi?',
  'Có việc nào cần đặt quy tắc rõ hơn?',
  'Có lỗi nào đến từ việc quá tải?',
  'Có lỗi nào đến từ việc không ghi lại?',
  'Có lỗi nào đến từ việc giao tiếp không rõ?',
  'Có điều gì hôm nay mày làm tốt hơn lần trước?',
  'Có thói quen xấu nào vừa lộ ra?',
  'Nếu sửa một thứ từ hôm nay, nó sẽ là gì?',
  'Có bài học nào đáng biến thành nguyên tắc?',
  'Có việc gì cần thử cách mới vào lần sau?',

  // Tương lai & quyết định
  'Có quyết định nào mày đang trì hoãn?',
  'Nếu phải quyết định ngay hôm nay, mày sẽ chọn gì?',
  'Điều gì có thể xảy ra trong 30 ngày tới mà mày nên chuẩn bị?',
  'Có việc gì hôm nay giúp tương lai dễ hơn?',
  'Có việc gì mày đang làm chỉ vì đã làm quá lâu?',
  'Mày muốn điều gì khác đi vào tuần sau?',
  'Có mục tiêu nào đang không còn đáng theo đuổi?',
  'Có mục tiêu nào cần chia nhỏ hơn?',
  'Điều gì nếu làm đều 30 ngày sẽ tạo khác biệt lớn?',
  'Có thứ gì mày muốn bắt đầu trước khi thấy “sẵn sàng”?',
  'Có điều gì cần đặt deadline cụ thể?',
  'Có quyết định nào nên thử nhỏ trước khi cam kết lớn?',
  'Rủi ro lớn nhất của việc mày đang làm là gì?',
  'Có phương án dự phòng nào cần chuẩn bị?',
  'Nếu kế hoạch hiện tại thất bại, nguyên nhân có thể là gì?',
  'Có việc nào nên làm sớm hơn 1 tuần?',
  'Có điều gì hôm nay đáng đưa vào kế hoạch tháng?',
  'Nếu một năm nữa nhìn lại, điều gì hôm nay có thể quan trọng?',
  'Có thứ gì mày muốn bỏ khỏi lịch tuần tới?',
  'Có điều gì mày muốn chắc chắn không quên vào ngày mai?',

  // Bản thân & nguyên tắc sống
  'Hôm nay mày làm điều gì đúng với kiểu người mày muốn trở thành?',
  'Có điều gì mày làm chỉ để làm hài lòng người khác?',
  'Có nguyên tắc nào hôm nay được kiểm chứng?',
  'Có điều gì mày đang tự lừa mình?',
  'Có thứ gì mày đang đánh giá quá cao?',
  'Có thứ gì mày đang đánh giá quá thấp?',
  'Điều gì mày thật sự muốn lúc này?',
  'Có việc nào mày làm vì sợ bỏ lỡ?',
  'Có điều gì mày muốn nói “không” nhiều hơn?',
  'Có điều gì mày muốn nói “có” nhiều hơn?',
  'Hôm nay mày đã dùng thời gian đúng với ưu tiên chưa?',
  'Có thứ gì mày đang theo đuổi mà không rõ lý do?',
  'Điều gì khiến mày cảm thấy mình đang tiến lên?',
  'Có thứ gì mày muốn làm ít đi?',
  'Có thứ gì mày muốn làm nhiều hơn?',
  'Có lúc nào hôm nay mày thấy mình thật sự tập trung?',
  'Có điều gì làm mày mất tập trung nhiều nhất?',
  'Có thứ gì đang chiếm đầu óc nhưng không đáng?',
  'Nếu hôm nay lặp lại 100 lần, cuộc sống sẽ đi về đâu?',
  'Một điều mày muốn cảm ơn bản thân hôm nay là gì?',
] as const;

function hashString(value: string): number {
  let hash = 2166136261;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

export function dailyNotePrompt(date: string, offset = 0): string {
  if (!DAILY_NOTE_PROMPTS.length) return 'Hôm nay có gì đáng nhớ?';
  const index = (hashString(date) + Math.max(0, Math.round(offset))) % DAILY_NOTE_PROMPTS.length;
  return DAILY_NOTE_PROMPTS[index];
}
